### PR TITLE
Issue: On demand page by page pagination

### PR DESCRIPTION
**Pull request by LeandroLuque**
A quick fix for #2. It's only implemented for  **Resultados** component, not **ResultadosCategoria".

### CODE REVIEW

**Comment by malerey** [comment]
Sorry @LeandroLuque but at least in my pc I see all the products displayed at once. No pagination at all. Can you check?

**Comment by LeandroLuque** [comment]
According to my output, each request to server get 8 elements (when it's possible). 
You can see "all products", but each page is loaded on demand.
I'll check it again.

**Comment by malerey** [comment]
@LeandroLuque i merged the request but it still has the same issue. it's online so you can check: https://singluten.now.sh/busqueda/aceite

**Comment by LeandroLuque** [comment]
@malerey  it's true, the url isn't working (126 instead of 8)
screenshot from 2018-09-16 14-53-38

**Comment by LeandroLuque** [comment]
100% confirmed. the bug is in the server side. The query (DB) doesn't process the parameters limit and offset. 
I have a local server and the new query (server/routes/busqueda.js) works fine.

**Comment by malerey** [comment]
I'll see what I can do. Thanks!

**Pull request merged**
